USE [master]
GO

/****** Object:  Database [JonasDB]    Script Date: 2/3/2020 1:51:33 AM ******/
CREATE DATABASE [JonasDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'temp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\JonasDB11.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [memory_optimized_filegroup_0] CONTAINS MEMORY_OPTIMIZED_DATA  DEFAULT
( NAME = N'memory_optimized_file_1817918590', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\memory_optimized_file_111817918590' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'temp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\JonasDB11_log.ldf' , SIZE = 2760704KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [JonasDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JonasDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JonasDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JonasDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JonasDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JonasDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JonasDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [JonasDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JonasDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JonasDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JonasDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JonasDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JonasDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JonasDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JonasDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JonasDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JonasDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [JonasDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JonasDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JonasDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JonasDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JonasDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JonasDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JonasDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JonasDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [JonasDB] SET  MULTI_USER 
GO

ALTER DATABASE [JonasDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JonasDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JonasDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JonasDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [JonasDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [JonasDB] SET QUERY_STORE = OFF
GO

USE [JonasDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [JonasDB] SET  READ_WRITE 
GO

